# Use mouse wheel to go to prev or next page
WheelForPaging=True
# Font
Font="MesloLGS Nerd Font,Sarasa Gothic SC,Noto Sans CJK SC 13"
# Menu Font
MenuFont="MesloLGS Nerd Font,Sarasa Gothic SC,Noto Sans CJK SC 11"
# Tray Font
TrayFont="MesloLGS Nerd Font,Sarasa Gothic SC,Noto Sans CJK SC Bold 10"
# Tray Label Outline Color
TrayOutlineColor=#1a1b26
# Tray Label Text Color
TrayTextColor=#c0caf5
# Prefer Text Icon
PreferTextIcon=False
# Show Layout Name In Icon
ShowLayoutNameInIcon=True
# Use input method language to display text
UseInputMethodLanguageToDisplayText=True
# Theme
Theme=tokyonight
# Dark Theme
DarkTheme=tokyonight
# Follow system light/dark color scheme
UseDarkTheme=False
# Follow system accent color if it is supported by theme and desktop
UseAccentColor=False
# Use Per Screen DPI on X11
PerScreenDPI=True
# Force font DPI on Wayland
ForceWaylandDPI=0
# Enable fractional scale under Wayland
EnableFractionalScale=True
